export default {
  "ORDER_ROUTING_APP_VIEW": "ORDER_ROUTING_APP_VIEW",
  "APP_TEST_DRIVE_VIEW": "APP_TEST_DRIVE_VIEW",
  "APP_PWA_STANDALONE_ACCESS": "APP_PWA_STANDALONE_ACCESS",
  "APP_COMMERCE_VIEW": "APP_COMMERCE_VIEW",
  "APP_PRODUCT_IDENTIFIER_UPDATE": "APP_PRODUCT_IDENTIFIER_UPDATE",
}