export default {
  "ORDER_ROUTING_APP_VIEW": "ORDER_ROUTING_APP_VIEW",
  "APP_TEST_DRIVE_VIEW": "ROUTING_TEST_DRIVE_VIEW",
  "APP_PWA_STANDALONE_ACCESS": "COMMON_ADMIN",
  "APP_PRODUCT_IDENTIFIER_UPDATE": "COMMON_ADMIN",
}