export const SN_PRODUCT = "product"
export const PRODUCT_LIST_UPDATED = SN_PRODUCT + "/LIST_UPDATED"
export const PRODUCT_STOCK_UPDATED = SN_PRODUCT + "/STOCK_UPDATED"
export const PRODUCT_CLEARED = SN_PRODUCT + "/CLEARED"

